language: php

php:
    - 5.2
    - 5.3.3
    - 5.3
    - 5.4

branches:
    only: master

notifications:
    email: false
    irc: "irc.iiens.net#Erebot"

before_script:
    - wget http://getcomposer.org/composer.phar
    - php composer.phar install --dev

script: phpunit --bootstrap vendor/erebot/testenv/bootstrap.php tests/

